markdown: rdiscount
pygments: true
permalink: /:title
auto: true
rdiscount:
  extensions: [smart]

name: James Shakespeare
url: http://jshak.es
description: Converting caffeine into code and cake into cadence.
twitter: jeshake
github: jshakes
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c